import { SEED_VERSION } from "@/lib/constants";
import type {
  Agent,
  Appointment,
  Contact,
  CRMSnapshot,
  Deal,
  Lead,
  LeadActivity,
  Property,
  PropertyImage,
  Task,
  Workspace,
} from "@/lib/types";
import { scoreLead } from "@/lib/ai/scoring";

const WS = "ws_meridian";
const now = "2026-08-18T10:00:00.000Z";

function iso(daysFromToday: number, hour = 10, minute = 0) {
  const d = new Date("2026-08-18T00:00:00.000Z");
  d.setUTCDate(d.getUTCDate() + daysFromToday);
  d.setUTCHours(hour, minute, 0, 0);
  return d.toISOString();
}

const PHOTO = [
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdbc?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600047509782-20d39509f26d?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?auto=format&fit=crop&w=1800&q=80",
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1800&q=80",
];

const workspace: Workspace = {
  id: WS,
  name: "Meridian Private Estates",
  slug: "meridian",
  tagline: "Quietly placing exceptional homes.",
  plan: "private",
  createdAt: iso(-400),
  updatedAt: now,
};

const agents: Agent[] = [
  {
    id: "agt_01",
    workspaceId: WS,
    name: "James Whitmore",
    email: "oscar.d@example.net",
    phone: "+44 20 7946 0101",
    title: "Managing Partner",
    city: "London",
    bio: "Leads Meridian’s private client desk across London and the Gulf. Twenty years in off-market residential.",
    avatarUrl: "https://i.pravatar.cc/256?img=12",
    role: "owner",
    specializations: ["Penthouses", "Off-market", "Family offices"],
    active: true,
    createdAt: iso(-400),
    updatedAt: now,
  },
  {
    id: "agt_02",
    workspaceId: WS,
    name: "Sofia Alvarez",
    email: "wendy.h@example.net",
    phone: "+1 305 555 0142",
    title: "Senior Partner, Americas",
    city: "Miami",
    bio: "Waterfront and new-development specialist covering Miami, Coral Gables, and the Caribbean corridor.",
    avatarUrl: "https://i.pravatar.cc/256?img=5",
    role: "admin",
    specializations: ["Waterfront", "New development"],
    active: true,
    createdAt: iso(-380),
    updatedAt: now,
  },
  {
    id: "agt_03",
    workspaceId: WS,
    name: "Kenji Nakamura",
    email: "ethan.b@example.com",
    phone: "++1-555-0014",
    title: "Luxury Specialist",
    city: "Dubai",
    bio: "Palm, Emirates Hills, and Downtown inventory for international buyers relocating to the UAE.",
    avatarUrl: "https://i.pravatar.cc/256?img=15",
    role: "agent",
    specializations: ["Villas", "International relocation"],
    active: true,
    createdAt: iso(-360),
    updatedAt: now,
  },
  {
    id: "agt_04",
    workspaceId: WS,
    name: "Amélie Laurent",
    email: "tom.h@example.org",
    phone: "+33 1 42 68 5300",
    title: "Senior Agent, Paris",
    city: "Paris",
    bio: "Left Bank residences and Haussmann apartments for discreet European families.",
    avatarUrl: "https://i.pravatar.cc/256?img=9",
    role: "agent",
    specializations: ["Historic homes", "Pied-à-terre"],
    active: true,
    createdAt: iso(-340),
    updatedAt: now,
  },
  {
    id: "agt_05",
    workspaceId: WS,
    name: "Marcus Chen",
    email: "beth.t@example.com",
    phone: "+65 6220 1188",
    title: "Director, Commercial & Prime",
    city: "Singapore",
    bio: "Sentosa Cove, Marina Bay, and selected commercial floors for family offices.",
    avatarUrl: "https://i.pravatar.cc/256?img=14",
    role: "agent",
    specializations: ["Commercial", "Waterfront villas"],
    active: true,
    createdAt: iso(-320),
    updatedAt: now,
  },
  {
    id: "agt_06",
    workspaceId: WS,
    name: "Olivia Bennett",
    email: "oscar.d@example.net",
    phone: "+1 212 555 0194",
    title: "Residential Director, New York",
    city: "New York",
    bio: "Manhattan loft conversions and full-floor residences below 14th Street and along the Hudson.",
    avatarUrl: "https://i.pravatar.cc/256?img=32",
    role: "agent",
    specializations: ["Lofts", "Full-floor residences"],
    active: true,
    createdAt: iso(-300),
    updatedAt: now,
  },
  {
    id: "agt_07",
    workspaceId: WS,
    name: "Luca Romano",
    email: "ivan.p@example.net",
    phone: "+34 93 272 0100",
    title: "Villa Specialist, Iberia",
    city: "Barcelona",
    bio: "Eixample townhouses and Sitges coast villas for Northern European buyers.",
    avatarUrl: "https://i.pravatar.cc/256?img=13",
    role: "agent",
    specializations: ["Villas", "Townhouses"],
    active: true,
    createdAt: iso(-280),
    updatedAt: now,
  },
  {
    id: "agt_08",
    workspaceId: WS,
    name: "Priya Sharma",
    email: "ethan.b@example.com",
    phone: "+971 4 365 2200",
    title: "New Developments Lead",
    city: "Dubai",
    bio: "Off-plan and branded residences across Dubai Marina, Downtown, and Dubai Hills.",
    avatarUrl: "https://i.pravatar.cc/256?img=20",
    role: "agent",
    specializations: ["Off-plan", "Branded residences"],
    active: true,
    createdAt: iso(-260),
    updatedAt: now,
  },
  {
    id: "agt_09",
    workspaceId: WS,
    name: "Hannah Walsh",
    email: "ursula.b@example.com",
    phone: "+1 416 555 0177",
    title: "Residential Advisor",
    city: "Toronto",
    bio: "Yorkville and Distillery District homes for first-time luxury buyers and downsizers.",
    avatarUrl: "https://i.pravatar.cc/256?img=47",
    role: "agent",
    specializations: ["Condos", "First-time luxury"],
    active: true,
    createdAt: iso(-240),
    updatedAt: now,
  },
  {
    id: "agt_10",
    workspaceId: WS,
    name: "Alexander Petrov",
    email: "zoe.m@example.net",
    phone: "+61 2 9251 4400",
    title: "Investment Advisor, ANZ",
    city: "Sydney",
    bio: "Eastern suburbs houses and CBD investment stock for private wealth clients.",
    avatarUrl: "https://i.pravatar.cc/256?img=33",
    role: "agent",
    specializations: ["Investments", "Houses"],
    active: true,
    createdAt: iso(-220),
    updatedAt: now,
  },
];

type PropertySeed = Omit<Property, "workspaceId" | "createdAt" | "updatedAt">;

const propertySeeds: PropertySeed[] = [
  {
    id: "prp_01",
    title: "Mayfair Residence",
    address: "14 Grosvenor Square",
    city: "London",
    country: "United Kingdom",
    price: 8450000,
    currency: "USD",
    propertyType: "Penthouse",
    bedrooms: 4,
    bathrooms: 4,
    area: 4120,
    description:
      "Full-floor penthouse on Grosvenor Square with 4 bedrooms, 4 bathrooms, and 4,120 sq ft of interior space. Listed features include a private lift, terrace, fireplace, wine cellar, and 2 parking spaces. Built in 2016. Assigned to James Whitmore.",
    features: ["Private lift", "Terrace", "Fireplace", "Wine cellar", "2 parking spaces", "Porter"],
    status: "Active",
    agentId: "agt_01",
    yearBuilt: 2016,
    parking: 2,
    views: 1840,
    listedAt: iso(-46),
  },
  {
    id: "prp_02",
    title: "Palm Jumeirah Garden Villa",
    address: "Frond G, Palm Jumeirah",
    city: "Dubai",
    country: "United Arab Emirates",
    price: 12900000,
    currency: "USD",
    propertyType: "Villa",
    bedrooms: 6,
    bathrooms: 7,
    area: 9800,
    description:
      "Garden villa on Palm Jumeirah Frond G with 6 bedrooms, 7 bathrooms, and 9,800 sq ft. Features a private beach access path, pool, staff quarters, smart home system, and 4-car garage. Built in 2019.",
    features: ["Private pool", "Beach access path", "Staff quarters", "Smart home", "4-car garage", "Landscaped garden"],
    status: "Active",
    agentId: "agt_03",
    yearBuilt: 2019,
    parking: 4,
    views: 2214,
    listedAt: iso(-38),
  },
  {
    id: "prp_03",
    title: "SoHo Loft 12B",
    address: "72 Greene Street, 12B",
    city: "New York",
    country: "United States",
    price: 3250000,
    currency: "USD",
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 2180,
    description:
      "Cast-iron loft conversion on Greene Street. 2 bedrooms, 2 bathrooms, 2,180 sq ft. Original columns, 11 ft ceilings, chef’s kitchen, and keyed elevator. Built 1892, renovated 2021.",
    features: ["11 ft ceilings", "Keyed elevator", "Original columns", "Chef’s kitchen", "Central air"],
    status: "Under Offer",
    agentId: "agt_06",
    yearBuilt: 1892,
    parking: 0,
    views: 960,
    listedAt: iso(-62),
  },
  {
    id: "prp_04",
    title: "Coral Gables Estate",
    address: "910 Alhambra Circle",
    city: "Miami",
    country: "United States",
    price: 6750000,
    currency: "USD",
    propertyType: "House",
    bedrooms: 5,
    bathrooms: 5,
    area: 6400,
    description:
      "Mediterranean house in Coral Gables with 5 bedrooms, 5 bathrooms, and 6,400 sq ft. Features a loggia, summer kitchen, pool, generator, and 3-car garage. Lot landscaped with mature oaks. Built 2008.",
    features: ["Pool", "Summer kitchen", "Loggia", "Generator", "3-car garage", "Impact glass"],
    status: "Active",
    agentId: "agt_02",
    yearBuilt: 2008,
    parking: 3,
    views: 1344,
    listedAt: iso(-21),
  },
  {
    id: "prp_05",
    title: "Hollywood Hills Modern",
    address: "2284 Sunset Plaza Drive",
    city: "Los Angeles",
    country: "United States",
    price: 9100000,
    currency: "USD",
    propertyType: "House",
    bedrooms: 4,
    bathrooms: 5,
    area: 5200,
    description:
      "Steel-and-glass house on Sunset Plaza Drive. 4 bedrooms, 5 bathrooms, 5,200 sq ft. Infinity pool, screening room, three-stop elevator, and two-car garage. Built 2018.",
    features: ["Infinity pool", "Screening room", "Elevator", "Floor-to-ceiling glass", "2-car garage"],
    status: "Active",
    agentId: "agt_02",
    yearBuilt: 2018,
    parking: 2,
    views: 1760,
    listedAt: iso(-17),
  },
  {
    id: "prp_06",
    title: "Saint-Germain Apartment",
    address: "8 Rue de Seine",
    city: "Paris",
    country: "France",
    price: 2890000,
    currency: "USD",
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    area: 1680,
    description:
      "Third-floor apartment on Rue de Seine. 3 bedrooms, 2 bathrooms, 1,680 sq ft. Herringbone parquet, two fireplaces, concierge, and cellar. Building dated 1854, interior renovated 2020.",
    features: ["Herringbone parquet", "Two fireplaces", "Concierge", "Cellar", "Lift"],
    status: "Active",
    agentId: "agt_04",
    yearBuilt: 1854,
    parking: 0,
    views: 888,
    listedAt: iso(-29),
  },
  {
    id: "prp_07",
    title: "Eixample Townhouse",
    address: "Carrer de València 312",
    city: "Barcelona",
    country: "Spain",
    price: 1850000,
    currency: "USD",
    propertyType: "Townhouse",
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    description:
      "Modernista townhouse in Eixample. 4 bedrooms, 3 bathrooms, 3,100 sq ft across four levels. Interior courtyard, roof terrace, and restored stained glass. Sold subject to completion records in the CRM.",
    features: ["Roof terrace", "Interior courtyard", "Stained glass", "Elevator", "Restored facade"],
    status: "Sold",
    agentId: "agt_07",
    yearBuilt: 1908,
    parking: 1,
    views: 640,
    listedAt: iso(-120),
  },
  {
    id: "prp_08",
    title: "Marina Bay Sky Residence",
    address: "8 Marina Boulevard, #68",
    city: "Singapore",
    country: "Singapore",
    price: 7400000,
    currency: "USD",
    propertyType: "Penthouse",
    bedrooms: 4,
    bathrooms: 4,
    area: 3900,
    description:
      "High-floor residence at Marina Bay. 4 bedrooms, 4 bathrooms, 3,900 sq ft. Private lift lobby, indoor-outdoor living room, club access, and 2 parking lots. Completed 2014.",
    features: ["Private lift lobby", "Club access", "Indoor-outdoor living", "2 parking lots", "Concierge"],
    status: "Active",
    agentId: "agt_05",
    yearBuilt: 2014,
    parking: 2,
    views: 1540,
    listedAt: iso(-33),
  },
  {
    id: "prp_09",
    title: "Bondi Coastal House",
    address: "42 Military Road, Dover Heights",
    city: "Sydney",
    country: "Australia",
    price: 4200000,
    currency: "USD",
    propertyType: "House",
    bedrooms: 4,
    bathrooms: 3,
    area: 3600,
    description:
      "Four-bedroom coastal house in Dover Heights. 3 bathrooms, 3,600 sq ft. North-facing terrace, double garage, pool, and solar. Built 2012.",
    features: ["Pool", "North-facing terrace", "Double garage", "Solar", "Open-plan kitchen"],
    status: "Active",
    agentId: "agt_10",
    yearBuilt: 2012,
    parking: 2,
    views: 1012,
    listedAt: iso(-14),
  },
  {
    id: "prp_10",
    title: "Yorkville Boutique Condo",
    address: "155 Cumberland Street, 1104",
    city: "Toronto",
    country: "Canada",
    price: 1125000,
    currency: "USD",
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1120,
    description:
      "Two-bedroom condo in Yorkville. 1,120 sq ft, 2 bathrooms. Building amenities listed: concierge, gym, visitor parking. Draft listing pending photography.",
    features: ["Concierge", "Gym", "Visitor parking", "In-suite laundry"],
    status: "Draft",
    agentId: "agt_09",
    yearBuilt: 2011,
    parking: 1,
    views: 120,
    listedAt: iso(-4),
  },
  {
    id: "prp_11",
    title: "Knightsbridge Garden Flat",
    address: "27 Basil Street",
    city: "London",
    country: "United Kingdom",
    price: 3980000,
    currency: "USD",
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 2140,
    description:
      "Lateral garden flat in Knightsbridge. 3 bedrooms, 3 bathrooms, 2,140 sq ft. Direct garden access, 24-hour porter, underground parking. Building 1890, remodelled 2017.",
    features: ["Garden access", "24-hour porter", "Underground parking", "Utility room"],
    status: "Active",
    agentId: "agt_01",
    yearBuilt: 1890,
    parking: 1,
    views: 770,
    listedAt: iso(-25),
  },
  {
    id: "prp_12",
    title: "Downtown Dubai Office Floor",
    address: "Boulevard Plaza Tower 1, Floor 22",
    city: "Dubai",
    country: "United Arab Emirates",
    price: 5600000,
    currency: "USD",
    propertyType: "Commercial",
    bedrooms: 0,
    bathrooms: 4,
    area: 8200,
    description:
      "Entire 22nd floor at Boulevard Plaza Tower 1. 8,200 sq ft of fitted office with 4 washrooms, reception, 12 enclosed rooms, and 8 parking bays. Fitted 2022.",
    features: ["Fitted office", "Reception", "12 enclosed rooms", "8 parking bays", "IT riser"],
    status: "Active",
    agentId: "agt_08",
    yearBuilt: 2010,
    parking: 8,
    views: 430,
    listedAt: iso(-51),
  },
  {
    id: "prp_13",
    title: "Tribeca Warehouse Conversion",
    address: "11 North Moore Street, PH",
    city: "New York",
    country: "United States",
    price: 4750000,
    currency: "USD",
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 2860,
    description:
      "Penthouse conversion in a former warehouse. 3 bedrooms, 3 bathrooms, 2,860 sq ft plus 640 sq ft roof terrace. Features listed: wood-burning fireplace, chef’s kitchen, private storage. Under offer.",
    features: ["Roof terrace", "Wood-burning fireplace", "Chef’s kitchen", "Private storage", "Keyed elevator"],
    status: "Under Offer",
    agentId: "agt_06",
    yearBuilt: 1910,
    parking: 0,
    views: 1188,
    listedAt: iso(-70),
  },
  {
    id: "prp_14",
    title: "South Beach Penthouse",
    address: "1000 South Pointe Drive, PH-A",
    city: "Miami",
    country: "United States",
    price: 11200000,
    currency: "USD",
    propertyType: "Penthouse",
    bedrooms: 4,
    bathrooms: 5,
    area: 5400,
    description:
      "Corner penthouse at South Pointe. 4 bedrooms, 5 bathrooms, 5,400 sq ft interior plus wrap terrace. Private elevator, summer kitchen on terrace, 3 assigned parking spaces, spa bath. Built 2016.",
    features: ["Wrap terrace", "Private elevator", "Summer kitchen", "3 parking spaces", "Spa bath"],
    status: "Active",
    agentId: "agt_02",
    yearBuilt: 2016,
    parking: 3,
    views: 1988,
    listedAt: iso(-11),
  },
  {
    id: "prp_15",
    title: "Malibu Ocean House",
    address: "27140 Malibu Cove Colony Drive",
    city: "Los Angeles",
    country: "United States",
    price: 18500000,
    currency: "USD",
    propertyType: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area: 6100,
    description:
      "Beach-side house in Malibu Cove Colony. 5 bedrooms, 6 bathrooms, 6,100 sq ft. Direct beach access, pool, guest suite, 4-car garage. Built 2004, systems updated 2023.",
    features: ["Direct beach access", "Pool", "Guest suite", "4-car garage", "Security system"],
    status: "Active",
    agentId: "agt_02",
    yearBuilt: 2004,
    parking: 4,
    views: 2402,
    listedAt: iso(-9),
  },
  {
    id: "prp_16",
    title: "Le Marais Hôtel Particulier",
    address: "12 Rue des Coutures Saint-Gervais",
    city: "Paris",
    country: "France",
    price: 6300000,
    currency: "USD",
    propertyType: "Townhouse",
    bedrooms: 6,
    bathrooms: 4,
    area: 5200,
    description:
      "Private townhouse in Le Marais. 6 bedrooms, 4 bathrooms, 5,200 sq ft plus courtyard. Listed as archived after the seller paused the mandate. Features: stone staircase, library, staff room, cellar.",
    features: ["Courtyard", "Stone staircase", "Library", "Staff room", "Cellar"],
    status: "Archived",
    agentId: "agt_04",
    yearBuilt: 1720,
    parking: 0,
    views: 510,
    listedAt: iso(-200),
  },
  {
    id: "prp_17",
    title: "Sitges Beach Villa",
    address: "Passeig Marítim 48",
    city: "Barcelona",
    country: "Spain",
    price: 3450000,
    currency: "USD",
    propertyType: "Villa",
    bedrooms: 5,
    bathrooms: 5,
    area: 4700,
    description:
      "Villa on the Sitges seafront promenade. 5 bedrooms, 5 bathrooms, 4,700 sq ft. Pool, roof solarium, garage for 2 cars, and separate guest studio. Built 2001.",
    features: ["Pool", "Roof solarium", "Guest studio", "2-car garage", "Seafront plot"],
    status: "Active",
    agentId: "agt_07",
    yearBuilt: 2001,
    parking: 2,
    views: 860,
    listedAt: iso(-19),
  },
  {
    id: "prp_18",
    title: "Sentosa Cove Waterfront",
    address: "18 Ocean Drive",
    city: "Singapore",
    country: "Singapore",
    price: 14800000,
    currency: "USD",
    propertyType: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area: 7200,
    description:
      "Waterfront villa on Ocean Drive, Sentosa Cove. 5 bedrooms, 6 bathrooms, 7,200 sq ft. Private berth, pool, lift, staff annex, and 4-car garage. Under offer. Completed 2015.",
    features: ["Private berth", "Pool", "Lift", "Staff annex", "4-car garage"],
    status: "Under Offer",
    agentId: "agt_05",
    yearBuilt: 2015,
    parking: 4,
    views: 1320,
    listedAt: iso(-44),
  },
  {
    id: "prp_19",
    title: "Paddington Terrace",
    address: "88 Windsor Street, Paddington",
    city: "Sydney",
    country: "Australia",
    price: 2150000,
    currency: "USD",
    propertyType: "Townhouse",
    bedrooms: 3,
    bathrooms: 2,
    area: 1980,
    description:
      "Victorian terrace in Paddington. 3 bedrooms, 2 bathrooms, 1,980 sq ft. Rear courtyard, attic studio, and cellar. Marked sold in the CRM.",
    features: ["Rear courtyard", "Attic studio", "Cellar", "Restored fireplaces"],
    status: "Sold",
    agentId: "agt_10",
    yearBuilt: 1885,
    parking: 0,
    views: 540,
    listedAt: iso(-150),
  },
  {
    id: "prp_20",
    title: "Distillery District Loft",
    address: "55 Mill Street, 408",
    city: "Toronto",
    country: "Canada",
    price: 890000,
    currency: "USD",
    propertyType: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    area: 780,
    description:
      "One-bedroom loft in the Distillery District. 780 sq ft, 1 bathroom. Exposed brick, 14 ft ceilings, in-suite laundry, and building concierge. Built 2009.",
    features: ["Exposed brick", "14 ft ceilings", "In-suite laundry", "Concierge"],
    status: "Active",
    agentId: "agt_09",
    yearBuilt: 2009,
    parking: 1,
    views: 404,
    listedAt: iso(-8),
  },
];

function imagesFor(propertyId: string, title: string, offset: number): PropertyImage[] {
  return [0, 1, 2, 3].map((i) => ({
    id: `img_${propertyId}_${i}`,
    propertyId,
    url: PHOTO[(offset + i) % PHOTO.length],
    alt: `${title} — photo ${i + 1}`,
    sortOrder: i,
  }));
}

const properties: Property[] = propertySeeds.map((p) => ({
  ...p,
  workspaceId: WS,
  createdAt: p.listedAt,
  updatedAt: now,
}));

const propertyImages: PropertyImage[] = propertySeeds.flatMap((p, idx) =>
  imagesFor(p.id, p.title, idx * 2),
);

const contacts: Contact[] = [
  { id: "ctc_01", workspaceId: WS, name: "Helena Crowe", email: "helena.crowe@example.com", phone: "+44 7700 900111", city: "London", type: "Buyer", notes: "Family office. Prefers Mayfair and Knightsbridge.", agentId: "agt_01", company: "Crowe Holdings", createdAt: iso(-40), updatedAt: now },
  { id: "ctc_02", workspaceId: WS, name: "Rashid Al Maktoum", email: "rashid.am@example.com", phone: "+971 50 111 2233", city: "Dubai", type: "Buyer", notes: "Relocating from Abu Dhabi. Palm villas only.", agentId: "agt_03", createdAt: iso(-36), updatedAt: now },
  { id: "ctc_03", workspaceId: WS, name: "Nina Patel", email: "nina.patel@example.com", phone: "+1 917 555 0108", city: "New York", type: "Buyer", notes: "Cash buyer for a SoHo or Tribeca loft.", agentId: "agt_06", company: "Patel Media", createdAt: iso(-33), updatedAt: now },
  { id: "ctc_04", workspaceId: WS, name: "Diego Vargas", email: "diego.vargas@example.com", phone: "+1 305 555 0199", city: "Miami", type: "Investor", notes: "Looking at South Beach and Coral Gables.", agentId: "agt_02", createdAt: iso(-30), updatedAt: now },
  { id: "ctc_05", workspaceId: WS, name: "Claire Moreau", email: "claire.moreau@example.com", phone: "+33 6 12 34 56 78", city: "Paris", type: "Seller", notes: "Considering a sale of a Left Bank pied-à-terre.", agentId: "agt_04", createdAt: iso(-28), updatedAt: now },
  { id: "ctc_06", workspaceId: WS, name: "Wei Lin", email: "wei.lin@example.com", phone: "+65 9000 1122", city: "Singapore", type: "Buyer", notes: "Family relocating from Hong Kong.", agentId: "agt_05", company: "Lin Capital", createdAt: iso(-26), updatedAt: now },
  { id: "ctc_07", workspaceId: WS, name: "Marta Soler", email: "marta.soler@example.com", phone: "+34 600 123 456", city: "Barcelona", type: "Buyer", notes: "Northern European client, Sitges preferred.", agentId: "agt_07", createdAt: iso(-24), updatedAt: now },
  { id: "ctc_08", workspaceId: WS, name: "Tom Hughes", email: "tom.hughes@example.com", phone: "+61 412 000 221", city: "Sydney", type: "Investor", notes: "Eastern suburbs yield plus a Bondi house.", agentId: "agt_10", createdAt: iso(-22), updatedAt: now },
  { id: "ctc_09", workspaceId: WS, name: "Ava Thompson", email: "ava.thompson@example.com", phone: "+1 416 555 0144", city: "Toronto", type: "Buyer", notes: "First luxury purchase, Yorkville budget.", agentId: "agt_09", createdAt: iso(-20), updatedAt: now },
  { id: "ctc_10", workspaceId: WS, name: "Omar Haddad", email: "omar.haddad@example.com", phone: "+971 55 987 1100", city: "Dubai", type: "Investor", notes: "Commercial floor in Downtown.", agentId: "agt_08", company: "Haddad Group", createdAt: iso(-18), updatedAt: now },
  { id: "ctc_11", workspaceId: WS, name: "Lauren Kim", email: "lauren.kim@example.com", phone: "+1 310 555 0160", city: "Los Angeles", type: "Buyer", notes: "Entertainment counsel. Hollywood Hills or Malibu.", agentId: "agt_02", createdAt: iso(-16), updatedAt: now },
  { id: "ctc_12", workspaceId: WS, name: "Felix Berg", email: "felix.berg@example.com", phone: "+44 7700 900222", city: "London", type: "Partner", notes: "Private bank introducer.", agentId: "agt_01", company: "Nordhaven Private Bank", createdAt: iso(-14), updatedAt: now },
  { id: "ctc_13", workspaceId: WS, name: "Isabelle Roux", email: "isabelle.roux@example.com", phone: "+33 6 98 76 54 32", city: "Paris", type: "Buyer", notes: "Looking at Saint-Germain, 3 bedrooms.", agentId: "agt_04", createdAt: iso(-12), updatedAt: now },
  { id: "ctc_14", workspaceId: WS, name: "Noah Adler", email: "noah.adler@example.com", phone: "+1 212 555 0171", city: "New York", type: "Seller", notes: "Tribeca penthouse currently under offer.", agentId: "agt_06", createdAt: iso(-10), updatedAt: now },
  { id: "ctc_15", workspaceId: WS, name: "Camila Rossi", email: "camila.rossi@example.com", phone: "+34 611 222 333", city: "Barcelona", type: "Buyer", notes: "Eixample after previous sale.", agentId: "agt_07", createdAt: iso(-8), updatedAt: now },
  { id: "ctc_16", workspaceId: WS, name: "Daniel Okafor", email: "daniel.okafor@example.com", phone: "+44 7700 900333", city: "London", type: "Investor", notes: "Pied-à-terre plus a rental in Zone 1.", agentId: "agt_01", createdAt: iso(-7), updatedAt: now },
  { id: "ctc_17", workspaceId: WS, name: "Mei Tan", email: "mei.tan@example.com", phone: "+65 8123 4455", city: "Singapore", type: "Buyer", notes: "Sentosa Cove waterfront brief.", agentId: "agt_05", createdAt: iso(-6), updatedAt: now },
  { id: "ctc_18", workspaceId: WS, name: "Harper Cole", email: "harper.cole@example.com", phone: "+1 416 555 0188", city: "Toronto", type: "Buyer", notes: "Distillery loft as a weekday pied-à-terre.", agentId: "agt_09", createdAt: iso(-5), updatedAt: now },
];

type LeadSeed = Omit<Lead, "workspaceId" | "score" | "scoreReason" | "nextAction" | "createdAt" | "updatedAt"> & {
  createdOffset: number;
};

const leadSeeds: LeadSeed[] = [
  { id: "led_01", name: "Helena Crowe", email: "helena.crowe@example.com", phone: "+44 7700 900111", budgetMin: 7000000, budgetMax: 9500000, preferredLocation: "London", propertyType: "Penthouse", source: "Referral", status: "Negotiating", assignedAgentId: "agt_01", interestedPropertyId: "prp_01", contactId: "ctc_01", timeline: "60 days", notes: "Wants a porter building and parking.", lastContactedAt: iso(-1, 16), createdOffset: -40 },
  { id: "led_02", name: "Rashid Al Maktoum", email: "rashid.am@example.com", phone: "+971 50 111 2233", budgetMin: 10000000, budgetMax: 15000000, preferredLocation: "Dubai", propertyType: "Villa", source: "Website", status: "Viewing", assignedAgentId: "agt_03", interestedPropertyId: "prp_02", contactId: "ctc_02", timeline: "90 days", notes: "Must have staff quarters.", lastContactedAt: iso(-2, 11), createdOffset: -36 },
  { id: "led_03", name: "Nina Patel", email: "nina.patel@example.com", phone: "+1 917 555 0108", budgetMin: 2800000, budgetMax: 3600000, preferredLocation: "New York", propertyType: "Apartment", source: "Instagram", status: "Won", assignedAgentId: "agt_06", interestedPropertyId: "prp_03", contactId: "ctc_03", timeline: "Immediate", notes: "Cash. Attorney already engaged.", lastContactedAt: iso(-3, 15), createdOffset: -33 },
  { id: "led_04", name: "Diego Vargas", email: "diego.vargas@example.com", phone: "+1 305 555 0199", budgetMin: 5000000, budgetMax: 8000000, preferredLocation: "Miami", propertyType: "House", source: "Open House", status: "Contacted", assignedAgentId: "agt_02", interestedPropertyId: "prp_04", contactId: "ctc_04", timeline: "6 months", notes: "Comparing Coral Gables and South Beach.", lastContactedAt: iso(-4, 14), createdOffset: -30 },
  { id: "led_05", name: "Claire Moreau", email: "claire.moreau@example.com", phone: "+33 6 12 34 56 78", budgetMin: 2500000, budgetMax: 3200000, preferredLocation: "Paris", propertyType: "Apartment", source: "Partner", status: "New", assignedAgentId: "agt_04", interestedPropertyId: "prp_06", contactId: "ctc_05", timeline: "Undecided", notes: "May sell first.", createdOffset: -28 },
  { id: "led_06", name: "Wei Lin", email: "wei.lin@example.com", phone: "+65 9000 1122", budgetMin: 6000000, budgetMax: 9000000, preferredLocation: "Singapore", propertyType: "Penthouse", source: "Referral", status: "Viewing", assignedAgentId: "agt_05", interestedPropertyId: "prp_08", contactId: "ctc_06", timeline: "45 days", notes: "School-run proximity is secondary; lift lobby is not.", lastContactedAt: iso(-1, 9), createdOffset: -26 },
  { id: "led_07", name: "Marta Soler", email: "marta.soler@example.com", phone: "+34 600 123 456", budgetMin: 3000000, budgetMax: 4000000, preferredLocation: "Barcelona", propertyType: "Villa", source: "Portal", status: "Contacted", assignedAgentId: "agt_07", interestedPropertyId: "prp_17", contactId: "ctc_07", timeline: "120 days", notes: "Wants a guest studio.", lastContactedAt: iso(-5, 12), createdOffset: -24 },
  { id: "led_08", name: "Tom Hughes", email: "tom.hughes@example.com", phone: "+61 412 000 221", budgetMin: 3500000, budgetMax: 5000000, preferredLocation: "Sydney", propertyType: "House", source: "Website", status: "Negotiating", assignedAgentId: "agt_10", interestedPropertyId: "prp_09", contactId: "ctc_08", timeline: "30 days", notes: "Finance pre-approved.", lastContactedAt: iso(-1, 8), createdOffset: -22 },
  { id: "led_09", name: "Ava Thompson", email: "ava.thompson@example.com", phone: "+1 416 555 0144", budgetMin: 900000, budgetMax: 1300000, preferredLocation: "Toronto", propertyType: "Apartment", source: "Instagram", status: "New", assignedAgentId: "agt_09", interestedPropertyId: "prp_10", contactId: "ctc_09", timeline: "90 days", notes: "First luxury purchase.", createdOffset: -20 },
  { id: "led_10", name: "Omar Haddad", email: "omar.haddad@example.com", phone: "+971 55 987 1100", budgetMin: 4500000, budgetMax: 6500000, preferredLocation: "Dubai", propertyType: "Commercial", source: "Cold Call", status: "Viewing", assignedAgentId: "agt_08", interestedPropertyId: "prp_12", contactId: "ctc_10", timeline: "60 days", notes: "Needs 8 parking bays.", lastContactedAt: iso(-2, 13), createdOffset: -18 },
  { id: "led_11", name: "Lauren Kim", email: "lauren.kim@example.com", phone: "+1 310 555 0160", budgetMin: 15000000, budgetMax: 20000000, preferredLocation: "Los Angeles", propertyType: "Villa", source: "Referral", status: "Viewing", assignedAgentId: "agt_02", interestedPropertyId: "prp_15", contactId: "ctc_11", timeline: "45 days", notes: "Privacy and beach access required.", lastContactedAt: iso(-1, 18), createdOffset: -16 },
  { id: "led_12", name: "Isabelle Roux", email: "isabelle.roux@example.com", phone: "+33 6 98 76 54 32", budgetMin: 2400000, budgetMax: 3100000, preferredLocation: "Paris", propertyType: "Apartment", source: "Website", status: "Contacted", assignedAgentId: "agt_04", interestedPropertyId: "prp_06", contactId: "ctc_13", timeline: "75 days", notes: "Must have a lift.", lastContactedAt: iso(-3, 10), createdOffset: -12 },
  { id: "led_13", name: "Noah Adler", email: "noah.adler@example.com", phone: "+1 212 555 0171", budgetMin: 4000000, budgetMax: 5200000, preferredLocation: "New York", propertyType: "Apartment", source: "Partner", status: "Negotiating", assignedAgentId: "agt_06", interestedPropertyId: "prp_13", contactId: "ctc_14", timeline: "21 days", notes: "Seller of the Tribeca penthouse; also browsing.", lastContactedAt: iso(-1, 12), createdOffset: -10 },
  { id: "led_14", name: "Camila Rossi", email: "camila.rossi@example.com", phone: "+34 611 222 333", budgetMin: 1500000, budgetMax: 2200000, preferredLocation: "Barcelona", propertyType: "Townhouse", source: "Open House", status: "Lost", assignedAgentId: "agt_07", interestedPropertyId: "prp_07", contactId: "ctc_15", timeline: "Expired", notes: "Purchased with another agency.", lastContactedAt: iso(-20, 11), createdOffset: -80 },
  { id: "led_15", name: "Daniel Okafor", email: "daniel.okafor@example.com", phone: "+44 7700 900333", budgetMin: 3000000, budgetMax: 4500000, preferredLocation: "London", propertyType: "Apartment", source: "Referral", status: "Contacted", assignedAgentId: "agt_01", interestedPropertyId: "prp_11", contactId: "ctc_16", timeline: "120 days", notes: "Investment plus occasional stay.", lastContactedAt: iso(-6, 15), createdOffset: -7 },
  { id: "led_16", name: "Mei Tan", email: "mei.tan@example.com", phone: "+65 8123 4455", budgetMin: 12000000, budgetMax: 16000000, preferredLocation: "Singapore", propertyType: "Villa", source: "Partner", status: "Negotiating", assignedAgentId: "agt_05", interestedPropertyId: "prp_18", contactId: "ctc_17", timeline: "30 days", notes: "Berth is a hard requirement.", lastContactedAt: iso(0, 8), createdOffset: -6 },
  { id: "led_17", name: "Harper Cole", email: "harper.cole@example.com", phone: "+1 416 555 0188", budgetMin: 750000, budgetMax: 950000, preferredLocation: "Toronto", propertyType: "Apartment", source: "Instagram", status: "New", assignedAgentId: "agt_09", interestedPropertyId: "prp_20", contactId: "ctc_18", timeline: "60 days", notes: "Weekday pied-à-terre.", createdOffset: -5 },
  { id: "led_18", name: "Samuel Wright", email: "samuel.wright@example.com", phone: "+44 7700 900444", budgetMin: 8000000, budgetMax: 12000000, preferredLocation: "London", propertyType: "Penthouse", source: "Portal", status: "New", assignedAgentId: "agt_01", timeline: "Undecided", notes: "Enquired via Rightmove-style portal. No viewing yet.", createdOffset: -3 },
  { id: "led_19", name: "Yara Nasser", email: "yara.nasser@example.com", phone: "+971 50 222 8899", budgetMin: 5000000, budgetMax: 7000000, preferredLocation: "Dubai", propertyType: "Commercial", source: "Website", status: "Contacted", assignedAgentId: "agt_08", interestedPropertyId: "prp_12", timeline: "90 days", notes: "Comparing two towers.", lastContactedAt: iso(-2, 17), createdOffset: -9 },
  { id: "led_20", name: "Benito Cruz", email: "benito.cruz@example.com", phone: "+1 305 555 0120", budgetMin: 9000000, budgetMax: 13000000, preferredLocation: "Miami", propertyType: "Penthouse", source: "Referral", status: "Viewing", assignedAgentId: "agt_02", interestedPropertyId: "prp_14", timeline: "45 days", notes: "Wants wrap terrace.", lastContactedAt: iso(-1, 19), createdOffset: -11 },
  { id: "led_21", name: "Freya Nilsson", email: "freya.nilsson@example.com", phone: "+46 70 111 2233", budgetMin: 1600000, budgetMax: 2100000, preferredLocation: "Barcelona", propertyType: "Townhouse", source: "Instagram", status: "New", assignedAgentId: "agt_07", timeline: "180 days", notes: "Remote enquiry from Stockholm.", createdOffset: -2 },
  { id: "led_22", name: "Jonathan Hale", email: "jonathan.hale@example.com", phone: "+1 212 555 0133", budgetMin: 3000000, budgetMax: 4000000, preferredLocation: "New York", propertyType: "Apartment", source: "Open House", status: "Lost", assignedAgentId: "agt_06", interestedPropertyId: "prp_03", timeline: "Expired", notes: "Lost on price.", lastContactedAt: iso(-18, 9), createdOffset: -55 },
  { id: "led_23", name: "Chiara Bianchi", email: "chiara.bianchi@example.com", phone: "+33 6 11 22 33 44", budgetMin: 5500000, budgetMax: 7000000, preferredLocation: "Paris", propertyType: "Townhouse", source: "Partner", status: "Contacted", assignedAgentId: "agt_04", interestedPropertyId: "prp_16", timeline: "6 months", notes: "Interested if the Marais house returns to market.", lastContactedAt: iso(-8, 11), createdOffset: -15 },
  { id: "led_24", name: "Owen Blake", email: "owen.blake@example.com", phone: "+61 400 111 222", budgetMin: 1800000, budgetMax: 2400000, preferredLocation: "Sydney", propertyType: "Townhouse", source: "Website", status: "Won", assignedAgentId: "agt_10", interestedPropertyId: "prp_19", timeline: "Closed", notes: "Paddington terrace exchanged.", lastContactedAt: iso(-12, 10), createdOffset: -90 },
  { id: "led_25", name: "Sana Kapoor", email: "sana.kapoor@example.com", phone: "+971 55 333 2211", budgetMin: 11000000, budgetMax: 14000000, preferredLocation: "Dubai", propertyType: "Villa", source: "Referral", status: "New", assignedAgentId: "agt_03", interestedPropertyId: "prp_02", timeline: "30 days", notes: "Second Palm villa for extended family.", createdOffset: -1 },
  { id: "led_26", name: "Michael Grant", email: "michael.grant@example.com", phone: "+1 310 555 0181", budgetMin: 7000000, budgetMax: 10000000, preferredLocation: "Los Angeles", propertyType: "House", source: "Portal", status: "Contacted", assignedAgentId: "agt_02", interestedPropertyId: "prp_05", timeline: "90 days", notes: "Wants a screening room.", lastContactedAt: iso(-4, 16), createdOffset: -13 },
  { id: "led_27", name: "Elena Popov", email: "elena.popov@example.com", phone: "+65 8234 5566", budgetMin: 6500000, budgetMax: 8000000, preferredLocation: "Singapore", propertyType: "Penthouse", source: "Cold Call", status: "New", assignedAgentId: "agt_05", interestedPropertyId: "prp_08", timeline: "Undecided", notes: "Inbound after a brochure download.", createdOffset: -2 },
  { id: "led_28", name: "James Okonkwo", email: "james.okonkwo@example.com", phone: "+44 7700 900555", budgetMin: 3500000, budgetMax: 4200000, preferredLocation: "London", propertyType: "Apartment", source: "Open House", status: "Viewing", assignedAgentId: "agt_01", interestedPropertyId: "prp_11", timeline: "45 days", notes: "Attended Knightsbridge open house.", lastContactedAt: iso(0, 9), createdOffset: -4 },
  { id: "led_29", name: "Rita Almeida", email: "rita.almeida@example.com", phone: "+1 416 555 0190", budgetMin: 1000000, budgetMax: 1400000, preferredLocation: "Toronto", propertyType: "Apartment", source: "Website", status: "Contacted", assignedAgentId: "agt_09", interestedPropertyId: "prp_10", timeline: "60 days", notes: "Wants visitor parking.", lastContactedAt: iso(-3, 14), createdOffset: -8 },
  { id: "led_30", name: "Hugo Marchand", email: "hugo.marchand@example.com", phone: "+33 6 55 44 33 22", budgetMin: 2600000, budgetMax: 3000000, preferredLocation: "Paris", propertyType: "Apartment", source: "Referral", status: "Negotiating", assignedAgentId: "agt_04", interestedPropertyId: "prp_06", timeline: "21 days", notes: "Offer discussion this week.", lastContactedAt: iso(0, 7), createdOffset: -14 },
];

function buildLeads(): Lead[] {
  return leadSeeds.map((seed) => {
    const { createdOffset, ...rest } = seed;
    const lead: Lead = {
      ...rest,
      workspaceId: WS,
      score: 0,
      scoreReason: "",
      nextAction: "",
      createdAt: iso(createdOffset, 9, 15),
      updatedAt: now,
    };
    const scored = scoreLead(lead, properties, []);
    return {
      ...lead,
      score: scored.score,
      scoreReason: scored.reason,
      nextAction: scored.nextAction,
    };
  });
}

const activityBlueprints: Array<Omit<LeadActivity, "id"> & { id?: string }> = [
  { leadId: "led_01", agentId: "agt_01", type: "call", title: "Discovery call", body: "Confirmed budget up to $9.5M and a preference for Grosvenor Square porter buildings.", createdAt: iso(-39, 11) },
  { leadId: "led_01", agentId: "agt_01", type: "viewing", title: "Viewing — Mayfair Residence", body: "Walked the terrace and wine cellar. Client asked for service charge schedule.", createdAt: iso(-12, 15) },
  { leadId: "led_01", agentId: "agt_01", type: "email", title: "Offer discussion", body: "Shared draft heads of terms at $8.2M. Awaiting family office sign-off.", createdAt: iso(-1, 16) },
  { leadId: "led_02", agentId: "agt_03", type: "note", title: "Brief recorded", body: "Staff quarters and a garden villa on Frond G or H. No apartments.", createdAt: iso(-36, 10) },
  { leadId: "led_02", agentId: "agt_03", type: "viewing", title: "First viewing — Palm villa", body: "Tour of pool, staff block, and beach path. Second viewing requested at dusk.", createdAt: iso(-8, 17) },
  { leadId: "led_03", agentId: "agt_06", type: "email", title: "Offer accepted", body: "All-cash offer on SoHo Loft 12B accepted. Attorney intro sent.", createdAt: iso(-6, 13) },
  { leadId: "led_03", agentId: "agt_06", type: "status_change", title: "Marked won", body: "Exchange scheduled. Commission reserved.", createdAt: iso(-3, 15) },
  { leadId: "led_04", agentId: "agt_02", type: "call", title: "Intro call", body: "Open-house follow-up. Interested in generator and impact glass.", createdAt: iso(-29, 14) },
  { leadId: "led_04", agentId: "agt_02", type: "email", title: "Brochure sent", body: "Coral Gables Estate packet plus three comparables.", createdAt: iso(-4, 14) },
  { leadId: "led_05", agentId: "agt_04", type: "note", title: "Inbound seller/buyer", body: "May list a smaller apartment first. No call completed yet.", createdAt: iso(-28, 9) },
  { leadId: "led_06", agentId: "agt_05", type: "viewing", title: "Marina Bay tour", body: "Inspected private lift lobby and club. Family returning Saturday.", createdAt: iso(-4, 16) },
  { leadId: "led_06", agentId: "agt_05", type: "call", title: "School-run discussion", body: "Confirmed lift lobby is non-negotiable; school distance is flexible.", createdAt: iso(-1, 9) },
  { leadId: "led_07", agentId: "agt_07", type: "email", title: "Sitges packet", body: "Sent floor plans and community rules for the seafront villa.", createdAt: iso(-5, 12) },
  { leadId: "led_08", agentId: "agt_10", type: "call", title: "Finance confirmed", body: "Pre-approval to $5M. Preparing an offer on Bondi Coastal House.", createdAt: iso(-3, 8) },
  { leadId: "led_08", agentId: "agt_10", type: "note", title: "Offer draft", body: "Suggested $4.05M with 28-day settlement.", createdAt: iso(-1, 8) },
  { leadId: "led_10", agentId: "agt_08", type: "viewing", title: "Floor walk-through", body: "IT riser and parking allocation checked. Fit-out photographs requested.", createdAt: iso(-5, 11) },
  { leadId: "led_11", agentId: "agt_02", type: "call", title: "Privacy brief", body: "Gate community and beach access are mandatory.", createdAt: iso(-15, 18) },
  { leadId: "led_11", agentId: "agt_02", type: "viewing", title: "Malibu preview", body: "Exterior and beach path only. Interior scheduled.", createdAt: iso(-3, 16) },
  { leadId: "led_12", agentId: "agt_04", type: "email", title: "Building specs", body: "Confirmed lift and concierge on Rue de Seine.", createdAt: iso(-3, 10) },
  { leadId: "led_13", agentId: "agt_06", type: "status_change", title: "Under offer", body: "Tribeca penthouse moved to under offer after second viewing.", createdAt: iso(-4, 12) },
  { leadId: "led_13", agentId: "agt_06", type: "note", title: "Counter-offer", body: "Buyer at $4.55M. Seller considering.", createdAt: iso(-1, 12) },
  { leadId: "led_14", agentId: "agt_07", type: "status_change", title: "Lost", body: "Client purchased an Eixample flat with a local boutique agency.", createdAt: iso(-20, 11) },
  { leadId: "led_15", agentId: "agt_01", type: "call", title: "Investment thesis", body: "Wants Knightsbridge for rental demand and occasional stays.", createdAt: iso(-6, 15) },
  { leadId: "led_16", agentId: "agt_05", type: "viewing", title: "Sentosa Cove", body: "Inspected berth and staff annex. Offer expected this week.", createdAt: iso(-2, 15) },
  { leadId: "led_16", agentId: "agt_05", type: "email", title: "SPA draft", body: "Counsel reviewing option clauses.", createdAt: iso(0, 8) },
  { leadId: "led_18", agentId: "agt_01", type: "note", title: "Portal enquiry", body: "No phone connect yet. Auto-ack sent.", createdAt: iso(-3, 7) },
  { leadId: "led_19", agentId: "agt_08", type: "call", title: "Tower comparison", body: "Boulevard Plaza vs Index Tower. Parking is the hinge.", createdAt: iso(-2, 17) },
  { leadId: "led_20", agentId: "agt_02", type: "viewing", title: "South Beach PH", body: "Wrap terrace and private elevator confirmed.", createdAt: iso(-1, 19) },
  { leadId: "led_22", agentId: "agt_06", type: "status_change", title: "Lost on price", body: "Would not exceed $3.0M on Greene Street.", createdAt: iso(-18, 9) },
  { leadId: "led_23", agentId: "agt_04", type: "note", title: "Watchlist", body: "Will revisit if Le Marais townhouse is reactivated.", createdAt: iso(-8, 11) },
  { leadId: "led_24", agentId: "agt_10", type: "status_change", title: "Won — Paddington", body: "Exchange completed. File in closing archive.", createdAt: iso(-12, 10) },
  { leadId: "led_26", agentId: "agt_02", type: "email", title: "Screening room spec", body: "Sent equipment list as installed at Hollywood Hills Modern.", createdAt: iso(-4, 16) },
  { leadId: "led_28", agentId: "agt_01", type: "viewing", title: "Knightsbridge open house", body: "Spent 40 minutes. Requested a second private visit.", createdAt: iso(0, 9) },
  { leadId: "led_29", agentId: "agt_09", type: "call", title: "Parking question", body: "Confirmed visitor parking in the Yorkville building.", createdAt: iso(-3, 14) },
  { leadId: "led_30", agentId: "agt_04", type: "call", title: "Offer prep", body: "Discussed €-equivalent and notary timeline.", createdAt: iso(-2, 18) },
  { leadId: "led_30", agentId: "agt_04", type: "email", title: "Notary intro", body: "Introduced Maître Elbaz for the Rue de Seine apartment.", createdAt: iso(0, 7) },
  { leadId: "led_09", agentId: "agt_09", type: "note", title: "New lead", body: "Instagram enquiry on the Yorkville draft listing.", createdAt: iso(-20, 12) },
  { leadId: "led_17", agentId: "agt_09", type: "note", title: "Pied-à-terre brief", body: "Weekday use only. Exposed brick preferred.", createdAt: iso(-5, 10) },
  { leadId: "led_21", agentId: "agt_07", type: "email", title: "Welcome sequence", body: "Sent Eixample and Sitges long-list. No reply yet.", createdAt: iso(-2, 8) },
  { leadId: "led_25", agentId: "agt_03", type: "note", title: "Family compound", body: "Wants a second Palm villa within two fronds of the first.", createdAt: iso(-1, 13) },
];

const leadActivities: LeadActivity[] = activityBlueprints.map((a, i) => ({
  ...a,
  id: `act_${String(i + 1).padStart(2, "0")}`,
}));

const deals: Deal[] = [
  { id: "deal_01", workspaceId: WS, title: "Mayfair Residence — Crowe", leadId: "led_01", propertyId: "prp_01", agentId: "agt_01", stage: "Negotiation", value: 8200000, commissionRate: 2.0, expectedClose: iso(28), notes: "Family office counsel reviewing heads of terms.", createdAt: iso(-12), updatedAt: now },
  { id: "deal_02", workspaceId: WS, title: "SoHo Loft 12B — Patel", leadId: "led_03", propertyId: "prp_03", agentId: "agt_06", stage: "Closed Won", value: 3250000, commissionRate: 2.5, expectedClose: iso(-2), notes: "Exchanged. Commission accrued.", createdAt: iso(-20), updatedAt: now },
  { id: "deal_03", workspaceId: WS, title: "Bondi Coastal House — Hughes", leadId: "led_08", propertyId: "prp_09", agentId: "agt_10", stage: "Proposal", value: 4050000, commissionRate: 2.0, expectedClose: iso(21), notes: "Offer letter in draft.", createdAt: iso(-3), updatedAt: now },
  { id: "deal_04", workspaceId: WS, title: "Sentosa Cove — Tan", leadId: "led_16", propertyId: "prp_18", agentId: "agt_05", stage: "Due Diligence", value: 14500000, commissionRate: 1.5, expectedClose: iso(18), notes: "Berth license under review.", createdAt: iso(-6), updatedAt: now },
  { id: "deal_05", workspaceId: WS, title: "Tribeca PH — Adler", leadId: "led_13", propertyId: "prp_13", agentId: "agt_06", stage: "Negotiation", value: 4550000, commissionRate: 2.25, expectedClose: iso(14), notes: "Counter at $4.55M.", createdAt: iso(-4), updatedAt: now },
  { id: "deal_06", workspaceId: WS, title: "Paddington Terrace — Blake", leadId: "led_24", propertyId: "prp_19", agentId: "agt_10", stage: "Closed Won", value: 2150000, commissionRate: 2.0, expectedClose: iso(-12), notes: "Settled.", createdAt: iso(-40), updatedAt: now },
  { id: "deal_07", workspaceId: WS, title: "South Beach PH — Cruz", leadId: "led_20", propertyId: "prp_14", agentId: "agt_02", stage: "Qualified", value: 10800000, commissionRate: 2.0, expectedClose: iso(40), notes: "Second viewing booked.", createdAt: iso(-2), updatedAt: now },
  { id: "deal_08", workspaceId: WS, title: "Marina Bay — Lin", leadId: "led_06", propertyId: "prp_08", agentId: "agt_05", stage: "Proposal", value: 7200000, commissionRate: 1.75, expectedClose: iso(25), notes: "Waiting on Saturday family tour.", createdAt: iso(-4), updatedAt: now },
  { id: "deal_09", workspaceId: WS, title: "Saint-Germain — Marchand", leadId: "led_30", propertyId: "prp_06", agentId: "agt_04", stage: "Negotiation", value: 2780000, commissionRate: 3.0, expectedClose: iso(16), notes: "Notary intro complete.", createdAt: iso(-5), updatedAt: now },
  { id: "deal_10", workspaceId: WS, title: "Eixample — Rossi", leadId: "led_14", propertyId: "prp_07", agentId: "agt_07", stage: "Closed Lost", value: 1850000, commissionRate: 3.0, expectedClose: iso(-20), notes: "Lost to local boutique.", createdAt: iso(-50), updatedAt: now },
];

const appointments: Appointment[] = [
  { id: "apt_01", workspaceId: WS, title: "Mayfair second viewing — Crowe", type: "Property Viewing", startAt: iso(0, 15, 0), endAt: iso(0, 16, 0), location: "14 Grosvenor Square", notes: "Bring service charge pack.", agentId: "agt_01", leadId: "led_01", propertyId: "prp_01", createdAt: iso(-4), updatedAt: now },
  { id: "apt_02", workspaceId: WS, title: "Palm villa dusk tour", type: "Property Viewing", startAt: iso(1, 17, 30), endAt: iso(1, 18, 30), location: "Frond G, Palm Jumeirah", notes: "Request lighting on for the garden.", agentId: "agt_03", leadId: "led_02", propertyId: "prp_02", createdAt: iso(-3), updatedAt: now },
  { id: "apt_03", workspaceId: WS, title: "Lin family — Marina Bay", type: "Property Viewing", startAt: iso(2, 11, 0), endAt: iso(2, 12, 0), location: "8 Marina Boulevard", notes: "Club access badges required.", agentId: "agt_05", leadId: "led_06", propertyId: "prp_08", createdAt: iso(-2), updatedAt: now },
  { id: "apt_04", workspaceId: WS, title: "Malibu interior — Kim", type: "Property Viewing", startAt: iso(3, 16, 0), endAt: iso(3, 17, 30), location: "27140 Malibu Cove Colony Drive", notes: "Security gate code in vault.", agentId: "agt_02", leadId: "led_11", propertyId: "prp_15", createdAt: iso(-2), updatedAt: now },
  { id: "apt_05", workspaceId: WS, title: "Hughes offer call", type: "Call", startAt: iso(0, 8, 30), endAt: iso(0, 9, 0), location: "Zoom", notes: "Walk the $4.05M structure.", agentId: "agt_10", leadId: "led_08", propertyId: "prp_09", createdAt: iso(-1), updatedAt: now },
  { id: "apt_06", workspaceId: WS, title: "Notary intro — Marchand", type: "Meeting", startAt: iso(1, 10, 0), endAt: iso(1, 11, 0), location: "8 Rue de Seine / video", notes: "Maître Elbaz joining.", agentId: "agt_04", leadId: "led_30", propertyId: "prp_06", createdAt: iso(-1), updatedAt: now },
  { id: "apt_07", workspaceId: WS, title: "Knightsbridge private return", type: "Property Viewing", startAt: iso(2, 14, 0), endAt: iso(2, 15, 0), location: "27 Basil Street", notes: "Okonkwo + partner.", agentId: "agt_01", leadId: "led_28", propertyId: "prp_11", createdAt: iso(0), updatedAt: now },
  { id: "apt_08", workspaceId: WS, title: "Downtown floor — Haddad", type: "Property Viewing", startAt: iso(4, 9, 0), endAt: iso(4, 10, 0), location: "Boulevard Plaza Tower 1", notes: "Facilities manager on site.", agentId: "agt_08", leadId: "led_10", propertyId: "prp_12", createdAt: iso(-2), updatedAt: now },
  { id: "apt_09", workspaceId: WS, title: "South Beach follow-up", type: "Follow-up", startAt: iso(1, 19, 0), endAt: iso(1, 19, 20), location: "Phone", notes: "After Cruz viewing.", agentId: "agt_02", leadId: "led_20", propertyId: "prp_14", createdAt: iso(-1), updatedAt: now },
  { id: "apt_10", workspaceId: WS, title: "Sentosa counsel call", type: "Call", startAt: iso(0, 13, 0), endAt: iso(0, 13, 30), location: "Conference line", notes: "Berth license questions.", agentId: "agt_05", leadId: "led_16", propertyId: "prp_18", createdAt: iso(-1), updatedAt: now },
  { id: "apt_11", workspaceId: WS, title: "Yorkville walk-through", type: "Property Viewing", startAt: iso(5, 12, 0), endAt: iso(5, 12, 45), location: "155 Cumberland Street", notes: "Draft listing — photography still pending.", agentId: "agt_09", leadId: "led_09", propertyId: "prp_10", createdAt: iso(-1), updatedAt: now },
  { id: "apt_12", workspaceId: WS, title: "Partner breakfast — Berg", type: "Meeting", startAt: iso(3, 8, 0), endAt: iso(3, 9, 0), location: "The Connaught, London", notes: "Private bank introductions.", agentId: "agt_01", createdAt: iso(-6), updatedAt: now },
  { id: "apt_13", workspaceId: WS, title: "Hollywood Hills — Grant", type: "Property Viewing", startAt: iso(6, 15, 0), endAt: iso(6, 16, 0), location: "2284 Sunset Plaza Drive", notes: "Screening room demo.", agentId: "agt_02", leadId: "led_26", propertyId: "prp_05", createdAt: iso(-2), updatedAt: now },
  { id: "apt_14", workspaceId: WS, title: "Sitges video tour", type: "Call", startAt: iso(2, 18, 0), endAt: iso(2, 18, 40), location: "Video", notes: "Soler is in Copenhagen this week.", agentId: "agt_07", leadId: "led_07", propertyId: "prp_17", createdAt: iso(-3), updatedAt: now },
  { id: "apt_15", workspaceId: WS, title: "Tribeca counter-offer", type: "Meeting", startAt: iso(1, 15, 0), endAt: iso(1, 16, 0), location: "Meridian NY office", notes: "Adler + counsel.", agentId: "agt_06", leadId: "led_13", propertyId: "prp_13", createdAt: iso(-1), updatedAt: now },
  { id: "apt_16", workspaceId: WS, title: "Distillery loft — Cole", type: "Property Viewing", startAt: iso(4, 17, 0), endAt: iso(4, 17, 30), location: "55 Mill Street", notes: "After-work slot.", agentId: "agt_09", leadId: "led_17", propertyId: "prp_20", createdAt: iso(-1), updatedAt: now },
  { id: "apt_17", workspaceId: WS, title: "Weekly pipeline review", type: "Meeting", startAt: iso(4, 8, 0), endAt: iso(4, 9, 0), location: "Meridian HQ / hybrid", notes: "All partners.", agentId: "agt_01", createdAt: iso(-10), updatedAt: now },
  { id: "apt_18", workspaceId: WS, title: "Nasser tower comparison", type: "Follow-up", startAt: iso(3, 11, 0), endAt: iso(3, 11, 20), location: "Phone", notes: "Send Index Tower comps.", agentId: "agt_08", leadId: "led_19", propertyId: "prp_12", createdAt: iso(-1), updatedAt: now },
  { id: "apt_19", workspaceId: WS, title: "Past — SoHo inspection", type: "Property Viewing", startAt: iso(-6, 11, 0), endAt: iso(-6, 12, 0), location: "72 Greene Street", notes: "Completed. Offer followed.", agentId: "agt_06", leadId: "led_03", propertyId: "prp_03", createdAt: iso(-10), updatedAt: now },
  { id: "apt_20", workspaceId: WS, title: "Past — Crowe first look", type: "Property Viewing", startAt: iso(-12, 15, 0), endAt: iso(-12, 16, 0), location: "14 Grosvenor Square", notes: "Completed.", agentId: "agt_01", leadId: "led_01", propertyId: "prp_01", createdAt: iso(-16), updatedAt: now },
];

const tasks: Task[] = [
  { id: "tsk_01", workspaceId: WS, title: "Send service charge pack — Mayfair", description: "Include the last three years and the sinking fund note.", dueAt: iso(0, 12), priority: "High", completed: false, agentId: "agt_01", leadId: "led_01", propertyId: "prp_01", createdAt: iso(-2), updatedAt: now },
  { id: "tsk_02", workspaceId: WS, title: "Draft Bondi offer letter", description: "$4.05M, 28-day settlement, 10% deposit.", dueAt: iso(0, 17), priority: "Urgent", completed: false, agentId: "agt_10", leadId: "led_08", propertyId: "prp_09", createdAt: iso(-1), updatedAt: now },
  { id: "tsk_03", workspaceId: WS, title: "Photography — Yorkville 1104", description: "Still a draft listing. Book twilight interiors.", dueAt: iso(2, 10), priority: "Medium", completed: false, agentId: "agt_09", propertyId: "prp_10", createdAt: iso(-3), updatedAt: now },
  { id: "tsk_04", workspaceId: WS, title: "Berth license checklist", description: "Sentosa Cove management pack for Mei Tan’s counsel.", dueAt: iso(1, 14), priority: "High", completed: false, agentId: "agt_05", leadId: "led_16", propertyId: "prp_18", createdAt: iso(-2), updatedAt: now },
  { id: "tsk_05", workspaceId: WS, title: "Call Claire Moreau", description: "Qualify whether she is selling or buying first.", dueAt: iso(1, 11), priority: "Medium", completed: false, agentId: "agt_04", leadId: "led_05", createdAt: iso(-1), updatedAt: now },
  { id: "tsk_06", workspaceId: WS, title: "Index Tower comps for Nasser", description: "Three commercial floors, parking ratios highlighted.", dueAt: iso(3, 9), priority: "Low", completed: false, agentId: "agt_08", leadId: "led_19", createdAt: iso(-1), updatedAt: now },
  { id: "tsk_07", workspaceId: WS, title: "Update portal copy — Palm villa", description: "Use only listed features. No invented marina views.", dueAt: iso(2, 16), priority: "Low", completed: false, agentId: "agt_03", propertyId: "prp_02", createdAt: iso(-4), updatedAt: now },
  { id: "tsk_08", workspaceId: WS, title: "SoHo closing checklist", description: "Attorney, deposit, and commission invoice.", dueAt: iso(-1, 17), priority: "High", completed: true, agentId: "agt_06", leadId: "led_03", propertyId: "prp_03", createdAt: iso(-8), updatedAt: now },
  { id: "tsk_09", workspaceId: WS, title: "Prepare Crowe heads of terms", description: "2% commission, parking included, 8-week completion.", dueAt: iso(1, 9), priority: "Urgent", completed: false, agentId: "agt_01", leadId: "led_01", propertyId: "prp_01", createdAt: iso(-1), updatedAt: now },
  { id: "tsk_10", workspaceId: WS, title: "Follow up Freya Nilsson", description: "No reply to the long-list email.", dueAt: iso(3, 15), priority: "Low", completed: false, agentId: "agt_07", leadId: "led_21", createdAt: iso(-1), updatedAt: now },
  { id: "tsk_11", workspaceId: WS, title: "Confirm gate code — Malibu", description: "Refresh vault entry before Kim’s interior tour.", dueAt: iso(2, 18), priority: "High", completed: false, agentId: "agt_02", leadId: "led_11", propertyId: "prp_15", createdAt: iso(-1), updatedAt: now },
  { id: "tsk_12", workspaceId: WS, title: "Issue commission note — Paddington", description: "Closed won. Finance to invoice.", dueAt: iso(-5, 12), priority: "Medium", completed: true, agentId: "agt_10", leadId: "led_24", propertyId: "prp_19", createdAt: iso(-10), updatedAt: now },
];

export function createSeedData(): CRMSnapshot {
  const leads = buildLeads();
  const scored = leads.map((lead) => {
    const acts = leadActivities.filter((a) => a.leadId === lead.id);
    const result = scoreLead(lead, properties, acts);
    return {
      ...lead,
      score: result.score,
      scoreReason: result.reason,
      nextAction: result.nextAction,
    };
  });

  return {
    seedVersion: SEED_VERSION,
    workspace,
    agents,
    properties,
    propertyImages,
    contacts,
    leads: scored,
    leadActivities,
    deals,
    appointments,
    tasks,
    aiGenerations: [],
  };
}
